### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by carrascomj** [biosustain/cameo#268]
Some breaking changes were introduced (mainly plotting #265) that invalidate part of the documentation/notebooks. Related issues:
* [ ] Fix inline markup (#188 )
* [ ] Sympy problem that [illustrates the changes in plotting](https://github.com/biosustain/cameo/issues/266#issuecomment-723698753) (#266).
* [ ] Check this old thread (#214).
* [ ] Check that this is clear (#238).
